#ifndef _CAR_H_
#define _CAR_H_

#include <cmgMath/cmg_math.h>
#include "TorqueCurve.h"
#include "Tire.h"

#define RADIANS_PER_SECOND_TO_RPM (60.0f / Math::TWO_PI)
#define METERS_PER_SECOND_TO_MPH 2.23694f


struct Gear
{
public:
	
	float m_ratio;
};



class Car
{
public:
	//-------------------------------------------------------------------------
	// Constructors & destructor
	Car();
	~Car();

	void Reset();

	//-------------------------------------------------------------------------
	// Car dynamics

	// Get the velocity of a point in world space that's connected to the car.
	Vector3f GetVelocityAtPoint(const Vector3f& point) const;

	void CalcDerivedData();
	void UpdatePhysics(float timeDelta);

	//-------------------------------------------------------------------------
	// Rigid body dynamics

	inline Vector3f GetForwardAxis() const { return m_orientation.GetForward(); }
	
	void AddForce(const Vector3f& force);
	void AddForce(const Vector3f& force, const Vector3f position);
	void Integrate(float timeDelta);
	void ClearAccumulators();

	//-------------------------------------------------------------------------
	// Transmission

	void ShiftUp();
	void ShiftDown();
	Gear& GetGear();

public:
	//-------------------------------------------------------------------------
	// Member variables

	// Current state
	Vector3f		m_position; // position of car is the center of all 4 wheels, on the ground
	Quaternion		m_orientation;
	Vector3f		m_velocity;
	Vector3f		m_angularVelocity;
	Vector3f		m_forceAccumulator;
	Vector3f		m_torqueAccumulator;
	float			m_engineSpeed; // Current engine speed in radians per second.
	unsigned int	m_gearIndex;
	float			m_steeringAngle;
	float			m_throttleAmount;
	float			m_handBreakAmount;
	float			m_reverseAmount;

	// Car properties
	float			m_mass; // Total car mass in kg
	float			m_centerOfMassHeight; // How high off the ground the center of mass is.
	float			m_centerOfMassOffset; // How in-front-of the car's positional center the center of mass is.
	float			m_gravity; // Acceleration due to gravity.
	float			m_densityOfAir; // kg/m^3
	float			m_inertia;
	Matrix3f		m_inertiaTensor;
	float			m_dragCoefficient;

	// General Dimensions
	Vector3f		m_chassisSize; // (x = width, y = height, z = length)
	float			m_wheelBase; // Longitudinal distance between front and rear wheel axels.
	float			m_wheelTrack; // Lateral distance between wheels on the same axel.
	float			m_frontalArea; // Used to calculate drag force.

	// Tire properties
	float			m_wheelRadius;
	unsigned int	m_numWheels;
	Tire			m_tires[4];
	float			m_tireFrictionCoefficient;
	float			m_rollingResistanceCoefficient;
	float			m_brakingTorque;

	// Engine
	float			m_engineIdleSpeed;
	float			m_engineRedLineSpeed;
	TorqueCurve		m_torqueCurve;

	// Drivetrain
	unsigned int	m_numGears;
	Gear			m_gears[5];
	float			m_finalDriveRatio;
	float			m_reverseGearRatio;
	float			m_transmissionEfficiency;
	float			m_driveTrainInertia;

public:
	//-------------------------------------------------------------------------
	// Derived data

	// Transformation matrices
	Matrix4f		m_worldToCar;
	Matrix4f		m_carToWorld;

	Matrix3f		m_inverseInertiaTensor;
	
	Vector3f		m_chassisTilt;
	Vector3f		m_weightTransferTorque;

	// Torques
	float			m_wheelTorque; // Torque passed to the wheels by the engine.
	float			m_engineTorque; // Maximum torque generated by the engine at its current speed (in Newton-meters).
	Vector3f		m_netTorque; // Net torque acting on the car body.

	// Forces
	Vector3f		m_netForce; // Net force acting on the car.
	Vector3f		m_dragForce;
	Vector3f		m_tractionForce;
	Vector3f		m_rollingResistanceForce;
};


#endif // _CAR_H_